#!/usr/bin/env julia
using Pkg
Pkg.activate("./MyPackage")

using MyPackage

# Define sdf parameters
sdf_type = "debye"
a = 0.3
T = 0.0
hc = 20
sdf = "./sdf/$(sdf_type)/$(sdf_type)_a_" * string(a) * "_T_" * string(T) * "_hc_" * string(hc) * ".json"
# Define TLS parameters
ϵ = 0.0
Δ = 0.2

# Run map_tomography
dt = 0.005
tau = 1
tomo = ["Up", "Dn", "+", "i"]
# tomo = ["Up"]
# tomo = ["Dn"]
# tomo = ["+"]
# tomo = ["i"] 
bd = 10
ld = 6
map_tomography(sdf, ϵ, Δ, dt, tau; growMPSval = bd, local_dim = ld, tomoStates = tomo)
