#!/usr/bin/env julia
using Pkg
Pkg.activate("./MyPackage")

using MyPackage

# Define sdf parameters
sdf_folder = "sdf-ohmic"
sdf_type = "ohmic"
a = 0.1
T = 0.0
sdf = "./sdf/$(sdf_folder)/$(sdf_type)_a_" * string(a) * "_T_" * string(T) * ".json"
# Define TLS parameters
ϵ = 0.0
Δ = 0.2

# Run map_tomography
my_dt = 0.005
map_tomography(sdf, ϵ, Δ; dt = my_dt, tmax = 30, growMPSval = 10, local_dim = 6)
