name = "SpinBosonDynamics"
uuid = "b92420a4-2619-4dec-98a9-0455795f3c57"
authors = ["Andrea Baroffio <andrea.baroff2000@gmail.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
MPSDynamics = "8fc8f346-e1eb-498f-94db-02ffe92d8134"

[compat]
DelimitedFiles = "1.9.1"
MPSDynamics = "1.1.0"
